import type { VectorTileLayer } from "../types"

const SOURCE = "base-map"

const classOf = ["get", "class"]

const inClass = (classes: string[]) => ["in", classOf, ["literal", classes]]

const nameField = ["coalesce", ["get", "name:latin"], ["get", "name"]]

const rankKey = ["coalesce", ["get", "rank"], 100]

const roadWidth = (boost: number) => [
  "interpolate",
  ["linear"],
  ["zoom"],
  4,
  [
    "+",
    [
      "match",
      classOf,
      "motorway",
      1.5,
      "trunk",
      1.3,
      "primary",
      1.1,
      "secondary",
      0.9,
      "tertiary",
      0.7,
      "minor",
      0.5,
      0.3,
    ],
    boost,
  ],
  12,
  [
    "+",
    [
      "match",
      classOf,
      "motorway",
      6,
      "trunk",
      5.4,
      "primary",
      4.6,
      "secondary",
      3.6,
      "tertiary",
      2.8,
      "minor",
      2,
      1.4,
    ],
    boost,
  ],
]

const labelHalo = {
  "text-halo-color": "rgba(255,255,255,0.9)",
  "text-halo-width": 1.2,
}

export const southIndiaLayers: VectorTileLayer[] = [
  {
    id: "background",
    type: "background",
    source: SOURCE,
    paint: { "background-color": "#f2efe9" },
  },
  {
    id: "water",
    type: "fill",
    source: SOURCE,
    "source-layer": "water",
    paint: { "fill-color": "#a3cddb", "fill-outline-color": "#8fbdd0" },
  },
  {
    id: "waterway",
    type: "line",
    source: SOURCE,
    "source-layer": "waterway",
    paint: {
      "line-color": "#a3cddb",
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 0.4, 12, 1.6],
    },
  },
  {
    id: "building",
    type: "fill",
    source: SOURCE,
    "source-layer": "building",
    minzoom: 13,
    paint: { "fill-color": "#e4ded2", "fill-outline-color": "#d5cdbe" },
  },
  {
    id: "road-casing",
    type: "line",
    source: SOURCE,
    "source-layer": "transportation",
    paint: { "line-color": "#c9c2b4", "line-width": roadWidth(1.8) },
  },
  {
    id: "road",
    type: "line",
    source: SOURCE,
    "source-layer": "transportation",
    paint: {
      "line-color": [
        "match",
        classOf,
        "motorway",
        "#e892a2",
        "trunk",
        "#ff8800",
        "primary",
        "#ff4400",
        "secondary",
        "#ffaa00",
        "tertiary",
        "#e8c86a",
        "minor",
        "#ffffff",
        "service",
        "#f7f4ef",
        "path",
        "#c3b9a8",
        "rail",
        "#a9a29a",
        "#ffffff",
      ],
      "line-width": roadWidth(0),
      "line-dasharray": [
        "case",
        inClass(["path", "footway", "steps", "track"]),
        ["literal", [2, 2]],
        ["case", inClass(["rail"]), ["literal", [3, 2]], ["literal", [1, 0]]],
      ],
    },
  },
  {
    id: "road-labels",
    type: "symbol",
    source: SOURCE,
    "source-layer": "transportation_name",
    minzoom: 12,
    layout: {
      "text-field": nameField,
      "text-font": ["Noto Sans Regular"],
      "text-size": ["interpolate", ["linear"], ["zoom"], 12, 9, 16, 12],
      "symbol-placement": "line",
      "text-max-width": 6,
      "symbol-sort-key": rankKey,
    },
    paint: { "text-color": "#6d6355", ...labelHalo },
  },
  {
    id: "place-dots",
    type: "circle",
    source: SOURCE,
    "source-layer": "place",
    filter: inClass(["city", "town", "village"]),
    paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 4, 1.5, 10, 3.5],
      "circle-color": "#4b4b4b",
      "circle-stroke-color": "#ffffff",
      "circle-stroke-width": 1,
    },
  },
  {
    id: "place-labels",
    type: "symbol",
    source: SOURCE,
    "source-layer": "place",
    layout: {
      "text-field": nameField,
      "text-anchor": "top",
      "text-offset": [0, 0.5],
      "text-font": [
        "match",
        classOf,
        "city",
        ["literal", ["Noto Sans Bold"]],
        "town",
        ["literal", ["Noto Sans Bold"]],
        ["literal", ["Noto Sans Regular"]],
      ],
      "text-size": [
        "interpolate",
        ["linear"],
        ["zoom"],
        4,
        [
          "match",
          classOf,
          "city",
          10,
          "town",
          9,
          "village",
          8,
          7.5,
        ],
        12,
        [
          "match",
          classOf,
          "city",
          15,
          "town",
          13,
          "village",
          11,
          9.5,
        ],
      ],
      "text-max-width": 7,
      "symbol-sort-key": rankKey,
    },
    paint: { "text-color": "#333333", ...labelHalo },
  },
  {
    id: "poi-dots",
    type: "circle",
    source: SOURCE,
    "source-layer": "poi",
    minzoom: 13,
    paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 13, 1.5, 16, 2.5],
      "circle-color": "#7a6f5d",
      "circle-stroke-color": "#ffffff",
      "circle-stroke-width": 0.8,
    },
  },
  {
    id: "poi-labels",
    type: "symbol",
    source: SOURCE,
    "source-layer": "poi",
    minzoom: 13,
    layout: {
      "text-field": nameField,
      "text-anchor": "top",
      "text-offset": [0, 0.8],
      "text-font": ["Noto Sans Regular"],
      "text-size": ["interpolate", ["linear"], ["zoom"], 13, 9, 16, 12],
      "text-max-width": 7,
      "symbol-sort-key": rankKey,
    },
    paint: { "text-color": "#5b5145", ...labelHalo },
  },
]
